# Generated by Django 4.1.4 on 2022-12-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateTimeField(default='26/12/2022'),
        ),
    ]
