# Generated by Django 4.1.4 on 2022-12-26 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 23, 25, 2, 240981, tzinfo=datetime.timezone.utc)),
        ),
    ]
